development:
  adapter: postgresql
  database: <%= Rails.application.secrets[:database] %>
  encoding: unicode
  pool: 5

test:
  adapter: postgresql
  database: <%= Rails.application.secrets[:database] %>
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  database: <%= Rails.application.secrets[:database] %>
  encoding: unicode
  pool: 5
