source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mysql2', '~> 0.3.18'
gem 'rails', '4.1.8'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'uglifier', '>= 1.3.0'
